language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t sirjohncabbage/docker-react -f Docerfile.dev .

script:
  - docker run -e CI=true sirjohncabbage/docker-react npm run test
